package club.ncr.website.db.auto;

import club.ncr.website.db.BbsTopic;
import org.apache.cayenne.CayenneDataObject;

import java.util.List;

/**
 * Class _BbsTopicType was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _BbsTopicType extends CayenneDataObject {

    public static final String NAME_PROPERTY = "name";
    public static final String TOPICS_PROPERTY = "topics";

    public static final String ID_PK_COLUMN = "ID";

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void addToTopics(BbsTopic obj) {
        addToManyTarget(TOPICS_PROPERTY, obj, true);
    }
    public void removeFromTopics(BbsTopic obj) {
        removeToManyTarget(TOPICS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<BbsTopic> getTopics() {
        return (List<BbsTopic>)readProperty(TOPICS_PROPERTY);
    }


}
