package club.ncr.website.db.auto;

import club.ncr.website.db.BbsPostType;
import club.ncr.website.db.BbsTopic;
import club.ncr.website.db.Contact;
import org.apache.cayenne.CayenneDataObject;

import java.util.Date;

/**
 * Class _BbsPost was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _BbsPost extends CayenneDataObject {

    public static final String CONTENT_PROPERTY = "content";
    public static final String DELETED_PROPERTY = "deleted";
    public static final String ID_PROPERTY = "id";
    public static final String LAST_READ_PROPERTY = "lastRead";
    public static final String POST_DATE_PROPERTY = "postDate";
    public static final String READS_PROPERTY = "reads";
    public static final String SUBJECT_PROPERTY = "subject";
    public static final String POSTED_BY_PROPERTY = "postedBy";
    public static final String TOPIC_PROPERTY = "topic";
    public static final String TYPE_PROPERTY = "type";

    public static final String ID_PK_COLUMN = "ID";

    public void setContent(String content) {
        writeProperty(CONTENT_PROPERTY, content);
    }
    public String getContent() {
        return (String)readProperty(CONTENT_PROPERTY);
    }

    public void setDeleted(Date deleted) {
        writeProperty(DELETED_PROPERTY, deleted);
    }
    public Date getDeleted() {
        return (Date)readProperty(DELETED_PROPERTY);
    }

    public void setId(Integer id) {
        writeProperty(ID_PROPERTY, id);
    }
    public Integer getId() {
        return (Integer)readProperty(ID_PROPERTY);
    }

    public void setLastRead(Date lastRead) {
        writeProperty(LAST_READ_PROPERTY, lastRead);
    }
    public Date getLastRead() {
        return (Date)readProperty(LAST_READ_PROPERTY);
    }

    public void setPostDate(Date postDate) {
        writeProperty(POST_DATE_PROPERTY, postDate);
    }
    public Date getPostDate() {
        return (Date)readProperty(POST_DATE_PROPERTY);
    }

    public void setReads(Integer reads) {
        writeProperty(READS_PROPERTY, reads);
    }
    public Integer getReads() {
        return (Integer)readProperty(READS_PROPERTY);
    }

    public void setSubject(String subject) {
        writeProperty(SUBJECT_PROPERTY, subject);
    }
    public String getSubject() {
        return (String)readProperty(SUBJECT_PROPERTY);
    }

    public void setPostedBy(Contact postedBy) {
        setToOneTarget(POSTED_BY_PROPERTY, postedBy, true);
    }

    public Contact getPostedBy() {
        return (Contact)readProperty(POSTED_BY_PROPERTY);
    }


    public void setTopic(BbsTopic topic) {
        setToOneTarget(TOPIC_PROPERTY, topic, true);
    }

    public BbsTopic getTopic() {
        return (BbsTopic)readProperty(TOPIC_PROPERTY);
    }


    public void setType(BbsPostType type) {
        setToOneTarget(TYPE_PROPERTY, type, true);
    }

    public BbsPostType getType() {
        return (BbsPostType)readProperty(TYPE_PROPERTY);
    }


}
