package club.ncr.website.db.auto;

import club.ncr.website.db.BbsPost;
import club.ncr.website.db.BbsTopicType;
import org.apache.cayenne.CayenneDataObject;

import java.util.List;

/**
 * Class _BbsTopic was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _BbsTopic extends CayenneDataObject {

    public static final String NAME_PROPERTY = "name";
    public static final String POSTS_PROPERTY = "posts";
    public static final String TYPE_PROPERTY = "type";

    public static final String ID_PK_COLUMN = "ID";

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void addToPosts(BbsPost obj) {
        addToManyTarget(POSTS_PROPERTY, obj, true);
    }
    public void removeFromPosts(BbsPost obj) {
        removeToManyTarget(POSTS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<BbsPost> getPosts() {
        return (List<BbsPost>)readProperty(POSTS_PROPERTY);
    }


    public void setType(BbsTopicType type) {
        setToOneTarget(TYPE_PROPERTY, type, true);
    }

    public BbsTopicType getType() {
        return (BbsTopicType)readProperty(TYPE_PROPERTY);
    }


}
