package club.ncr.website.db.auto;

import club.ncr.website.db.CalendarEventType;
import org.apache.cayenne.CayenneDataObject;

import java.util.Date;

/**
 * Class _CalendarEvent was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _CalendarEvent extends CayenneDataObject {

    public static final String DESCRIPTION_PROPERTY = "description";
    public static final String DURATION_PROPERTY = "duration";
    public static final String DURATION_UNITS_PROPERTY = "durationUnits";
    public static final String EVENT_DATE_PROPERTY = "eventDate";
    public static final String EVENT_TIME_PROPERTY = "eventTime";
    public static final String ID_PROPERTY = "id";
    public static final String TITLE_PROPERTY = "title";
    public static final String EVENT_TYPE_PROPERTY = "eventType";

    public static final String ID_PK_COLUMN = "ID";

    public void setDescription(String description) {
        writeProperty(DESCRIPTION_PROPERTY, description);
    }
    public String getDescription() {
        return (String)readProperty(DESCRIPTION_PROPERTY);
    }

    public void setDuration(Integer duration) {
        writeProperty(DURATION_PROPERTY, duration);
    }
    public Integer getDuration() {
        return (Integer)readProperty(DURATION_PROPERTY);
    }

    public void setDurationUnits(String durationUnits) {
        writeProperty(DURATION_UNITS_PROPERTY, durationUnits);
    }
    public String getDurationUnits() {
        return (String)readProperty(DURATION_UNITS_PROPERTY);
    }

    public void setEventDate(Date eventDate) {
        writeProperty(EVENT_DATE_PROPERTY, eventDate);
    }
    public Date getEventDate() {
        return (Date)readProperty(EVENT_DATE_PROPERTY);
    }

    public void setEventTime(Date eventTime) {
        writeProperty(EVENT_TIME_PROPERTY, eventTime);
    }
    public Date getEventTime() {
        return (Date)readProperty(EVENT_TIME_PROPERTY);
    }

    public void setId(Integer id) {
        writeProperty(ID_PROPERTY, id);
    }
    public Integer getId() {
        return (Integer)readProperty(ID_PROPERTY);
    }

    public void setTitle(String title) {
        writeProperty(TITLE_PROPERTY, title);
    }
    public String getTitle() {
        return (String)readProperty(TITLE_PROPERTY);
    }

    public void setEventType(CalendarEventType eventType) {
        setToOneTarget(EVENT_TYPE_PROPERTY, eventType, true);
    }

    public CalendarEventType getEventType() {
        return (CalendarEventType)readProperty(EVENT_TYPE_PROPERTY);
    }


}
