package club.ncr.website.db.auto;

import club.ncr.website.db.CalendarEvent;
import org.apache.cayenne.CayenneDataObject;

import java.util.List;

/**
 * Class _CalendarEventType was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _CalendarEventType extends CayenneDataObject {

    public static final String NAME_PROPERTY = "name";
    public static final String EVENTS_PROPERTY = "events";

    public static final String ID_PK_COLUMN = "ID";

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void addToEvents(CalendarEvent obj) {
        addToManyTarget(EVENTS_PROPERTY, obj, true);
    }
    public void removeFromEvents(CalendarEvent obj) {
        removeToManyTarget(EVENTS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<CalendarEvent> getEvents() {
        return (List<CalendarEvent>)readProperty(EVENTS_PROPERTY);
    }


}
