package club.ncr.website.db.auto;

import club.ncr.website.db.Contact;
import org.apache.cayenne.CayenneDataObject;

import java.util.Date;

/**
 * Class _ContactAddress was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ContactAddress extends CayenneDataObject {

    public static final String ADDRESS11_PROPERTY = "address11";
    public static final String ADDRESS21_PROPERTY = "address21";
    public static final String CITY1_PROPERTY = "city1";
    public static final String CONTACT_ID_PROPERTY = "contactId";
    public static final String COUNTRY1_PROPERTY = "country1";
    public static final String CREATED1_PROPERTY = "created1";
    public static final String LABEL1_PROPERTY = "label1";
    public static final String STATE1_PROPERTY = "state1";
    public static final String VERIFIED1_PROPERTY = "verified1";
    public static final String ZIP1_PROPERTY = "zip1";
    public static final String ZIP41_PROPERTY = "zip41";
    public static final String CONTACT_PROPERTY = "contact";

    public static final String ID_PK_COLUMN = "id";

    public void setAddress11(String address11) {
        writeProperty(ADDRESS11_PROPERTY, address11);
    }
    public String getAddress11() {
        return (String)readProperty(ADDRESS11_PROPERTY);
    }

    public void setAddress21(String address21) {
        writeProperty(ADDRESS21_PROPERTY, address21);
    }
    public String getAddress21() {
        return (String)readProperty(ADDRESS21_PROPERTY);
    }

    public void setCity1(String city1) {
        writeProperty(CITY1_PROPERTY, city1);
    }
    public String getCity1() {
        return (String)readProperty(CITY1_PROPERTY);
    }

    public void setContactId(Long contactId) {
        writeProperty(CONTACT_ID_PROPERTY, contactId);
    }
    public Long getContactId() {
        return (Long)readProperty(CONTACT_ID_PROPERTY);
    }

    public void setCountry1(String country1) {
        writeProperty(COUNTRY1_PROPERTY, country1);
    }
    public String getCountry1() {
        return (String)readProperty(COUNTRY1_PROPERTY);
    }

    public void setCreated1(Date created1) {
        writeProperty(CREATED1_PROPERTY, created1);
    }
    public Date getCreated1() {
        return (Date)readProperty(CREATED1_PROPERTY);
    }

    public void setLabel1(String label1) {
        writeProperty(LABEL1_PROPERTY, label1);
    }
    public String getLabel1() {
        return (String)readProperty(LABEL1_PROPERTY);
    }

    public void setState1(String state1) {
        writeProperty(STATE1_PROPERTY, state1);
    }
    public String getState1() {
        return (String)readProperty(STATE1_PROPERTY);
    }

    public void setVerified1(Date verified1) {
        writeProperty(VERIFIED1_PROPERTY, verified1);
    }
    public Date getVerified1() {
        return (Date)readProperty(VERIFIED1_PROPERTY);
    }

    public void setZip1(String zip1) {
        writeProperty(ZIP1_PROPERTY, zip1);
    }
    public String getZip1() {
        return (String)readProperty(ZIP1_PROPERTY);
    }

    public void setZip41(String zip41) {
        writeProperty(ZIP41_PROPERTY, zip41);
    }
    public String getZip41() {
        return (String)readProperty(ZIP41_PROPERTY);
    }

    public void setContact(Contact contact) {
        setToOneTarget(CONTACT_PROPERTY, contact, true);
    }

    public Contact getContact() {
        return (Contact)readProperty(CONTACT_PROPERTY);
    }


}
