package club.ncr.website.db.auto;

import club.ncr.website.db.Contact;
import org.apache.cayenne.CayenneDataObject;

import java.util.Date;

/**
 * Class _ContactPhone was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ContactPhone extends CayenneDataObject {

    public static final String AREA_CODE_PROPERTY = "areaCode";
    public static final String COUNTRY_CODE_PROPERTY = "countryCode";
    public static final String CREATED_PROPERTY = "created";
    public static final String EXT_PROPERTY = "ext";
    public static final String LABEL_PROPERTY = "label";
    public static final String LINE_PROPERTY = "line";
    public static final String NPA_PROPERTY = "npa";
    public static final String NXX_PROPERTY = "nxx";
    public static final String VERIFIED_PROPERTY = "verified";
    public static final String CONTACT_PROPERTY = "contact";

    public static final String ID_PK_COLUMN = "id";

    public void setAreaCode(String areaCode) {
        writeProperty(AREA_CODE_PROPERTY, areaCode);
    }
    public String getAreaCode() {
        return (String)readProperty(AREA_CODE_PROPERTY);
    }

    public void setCountryCode(String countryCode) {
        writeProperty(COUNTRY_CODE_PROPERTY, countryCode);
    }
    public String getCountryCode() {
        return (String)readProperty(COUNTRY_CODE_PROPERTY);
    }

    public void setCreated(Date created) {
        writeProperty(CREATED_PROPERTY, created);
    }
    public Date getCreated() {
        return (Date)readProperty(CREATED_PROPERTY);
    }

    public void setExt(String ext) {
        writeProperty(EXT_PROPERTY, ext);
    }
    public String getExt() {
        return (String)readProperty(EXT_PROPERTY);
    }

    public void setLabel(String label) {
        writeProperty(LABEL_PROPERTY, label);
    }
    public String getLabel() {
        return (String)readProperty(LABEL_PROPERTY);
    }

    public void setLine(String line) {
        writeProperty(LINE_PROPERTY, line);
    }
    public String getLine() {
        return (String)readProperty(LINE_PROPERTY);
    }

    public void setNpa(String npa) {
        writeProperty(NPA_PROPERTY, npa);
    }
    public String getNpa() {
        return (String)readProperty(NPA_PROPERTY);
    }

    public void setNxx(String nxx) {
        writeProperty(NXX_PROPERTY, nxx);
    }
    public String getNxx() {
        return (String)readProperty(NXX_PROPERTY);
    }

    public void setVerified(Date verified) {
        writeProperty(VERIFIED_PROPERTY, verified);
    }
    public Date getVerified() {
        return (Date)readProperty(VERIFIED_PROPERTY);
    }

    public void setContact(Contact contact) {
        setToOneTarget(CONTACT_PROPERTY, contact, true);
    }

    public Contact getContact() {
        return (Contact)readProperty(CONTACT_PROPERTY);
    }


}
