package club.ncr.website.db.auto;

import club.ncr.website.db.Contact;
import org.apache.cayenne.CayenneDataObject;

import java.util.Date;

/**
 * Class _ContactEmail was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ContactEmail extends CayenneDataObject {

    public static final String ADDRESS_PROPERTY = "address";
    public static final String VERIFIED_PROPERTY = "verified";
    public static final String CONTACT_PROPERTY = "contact";

    public static final String ID_PK_COLUMN = "id";

    public void setAddress(String address) {
        writeProperty(ADDRESS_PROPERTY, address);
    }
    public String getAddress() {
        return (String)readProperty(ADDRESS_PROPERTY);
    }

    public void setVerified(Date verified) {
        writeProperty(VERIFIED_PROPERTY, verified);
    }
    public Date getVerified() {
        return (Date)readProperty(VERIFIED_PROPERTY);
    }

    public void setContact(Contact contact) {
        setToOneTarget(CONTACT_PROPERTY, contact, true);
    }

    public Contact getContact() {
        return (Contact)readProperty(CONTACT_PROPERTY);
    }


}
