package club.ncr.website.db.auto;

import club.ncr.website.db.FlightLog;
import org.apache.cayenne.CayenneDataObject;

import java.util.Date;
import java.util.List;

/**
 * Class _FlightEvent was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _FlightEvent extends CayenneDataObject {

    public static final String DESCRIPTION_PROPERTY = "description";
    public static final String EVENT_DATE_PROPERTY = "eventDate";
    public static final String ID_PROPERTY = "id";
    public static final String LOCATION_PROPERTY = "location";
    public static final String TITLE_PROPERTY = "title";
    public static final String WEATHER_CONDITIONS_PROPERTY = "weatherConditions";
    public static final String LAUNCH_LOGS_PROPERTY = "launchLogs";

    public static final String ID_PK_COLUMN = "id";

    public void setDescription(String description) {
        writeProperty(DESCRIPTION_PROPERTY, description);
    }
    public String getDescription() {
        return (String)readProperty(DESCRIPTION_PROPERTY);
    }

    public void setEventDate(Date eventDate) {
        writeProperty(EVENT_DATE_PROPERTY, eventDate);
    }
    public Date getEventDate() {
        return (Date)readProperty(EVENT_DATE_PROPERTY);
    }

    public void setId(Integer id) {
        writeProperty(ID_PROPERTY, id);
    }
    public Integer getId() {
        return (Integer)readProperty(ID_PROPERTY);
    }

    public void setLocation(String location) {
        writeProperty(LOCATION_PROPERTY, location);
    }
    public String getLocation() {
        return (String)readProperty(LOCATION_PROPERTY);
    }

    public void setTitle(String title) {
        writeProperty(TITLE_PROPERTY, title);
    }
    public String getTitle() {
        return (String)readProperty(TITLE_PROPERTY);
    }

    public void setWeatherConditions(String weatherConditions) {
        writeProperty(WEATHER_CONDITIONS_PROPERTY, weatherConditions);
    }
    public String getWeatherConditions() {
        return (String)readProperty(WEATHER_CONDITIONS_PROPERTY);
    }

    public void addToLaunchLogs(FlightLog obj) {
        addToManyTarget(LAUNCH_LOGS_PROPERTY, obj, true);
    }
    public void removeFromLaunchLogs(FlightLog obj) {
        removeToManyTarget(LAUNCH_LOGS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<FlightLog> getLaunchLogs() {
        return (List<FlightLog>)readProperty(LAUNCH_LOGS_PROPERTY);
    }


}
