package club.ncr.website.db.auto;

import org.apache.cayenne.CayenneDataObject;

import java.util.Date;

/**
 * Class _LegacyLaunchEvent was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _LegacyLaunchEvent extends CayenneDataObject {

    public static final String CLUB_LAUNCH_PROPERTY = "clubLaunch";
    public static final String CREATED_DATE_PROPERTY = "createdDate";
    public static final String DESCRIPTION_PROPERTY = "description";
    public static final String LAUNCH_DATE_PROPERTY = "launchDate";
    public static final String LOCATION_PROPERTY = "location";
    public static final String NAME_PROPERTY = "name";
    public static final String WEATHER_PROPERTY = "weather";

    public static final String ID_PK_COLUMN = "id";

    public void setClubLaunch(String clubLaunch) {
        writeProperty(CLUB_LAUNCH_PROPERTY, clubLaunch);
    }
    public String getClubLaunch() {
        return (String)readProperty(CLUB_LAUNCH_PROPERTY);
    }

    public void setCreatedDate(Date createdDate) {
        writeProperty(CREATED_DATE_PROPERTY, createdDate);
    }
    public Date getCreatedDate() {
        return (Date)readProperty(CREATED_DATE_PROPERTY);
    }

    public void setDescription(String description) {
        writeProperty(DESCRIPTION_PROPERTY, description);
    }
    public String getDescription() {
        return (String)readProperty(DESCRIPTION_PROPERTY);
    }

    public void setLaunchDate(Date launchDate) {
        writeProperty(LAUNCH_DATE_PROPERTY, launchDate);
    }
    public Date getLaunchDate() {
        return (Date)readProperty(LAUNCH_DATE_PROPERTY);
    }

    public void setLocation(String location) {
        writeProperty(LOCATION_PROPERTY, location);
    }
    public String getLocation() {
        return (String)readProperty(LOCATION_PROPERTY);
    }

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void setWeather(String weather) {
        writeProperty(WEATHER_PROPERTY, weather);
    }
    public String getWeather() {
        return (String)readProperty(WEATHER_PROPERTY);
    }

}
