package club.ncr.website.db.auto;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _LegacyLevelType was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _LegacyLevelType extends CayenneDataObject {

    public static final String DESCRIPTION_PROPERTY = "description";
    public static final String ID_PROPERTY = "id";

    public static final String ID_PK_COLUMN = "id";

    public void setDescription(String description) {
        writeProperty(DESCRIPTION_PROPERTY, description);
    }
    public String getDescription() {
        return (String)readProperty(DESCRIPTION_PROPERTY);
    }

    public void setId(Byte id) {
        writeProperty(ID_PROPERTY, id);
    }
    public Byte getId() {
        return (Byte)readProperty(ID_PROPERTY);
    }

}
