package club.ncr.website.db.auto;

import club.ncr.website.db.Motor;
import club.ncr.website.db.MotorDataFormat;
import org.apache.cayenne.CayenneDataObject;

/**
 * Class _MotorData was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _MotorData extends CayenneDataObject {

    public static final String DATA_PROPERTY = "data";
    public static final String DATA_URL_PROPERTY = "dataUrl";
    public static final String INFO_URL_PROPERTY = "infoUrl";
    public static final String LICENSE_PROPERTY = "license";
    public static final String SOURCE_PROPERTY = "source";
    public static final String TC_FILE_ID_PROPERTY = "tcFileID";
    public static final String FORMAT_PROPERTY = "format";
    public static final String MOTOR_PROPERTY = "motor";

    public static final String ID_PK_COLUMN = "id";

    public void setData(byte[] data) {
        writeProperty(DATA_PROPERTY, data);
    }
    public byte[] getData() {
        return (byte[])readProperty(DATA_PROPERTY);
    }

    public void setDataUrl(String dataUrl) {
        writeProperty(DATA_URL_PROPERTY, dataUrl);
    }
    public String getDataUrl() {
        return (String)readProperty(DATA_URL_PROPERTY);
    }

    public void setInfoUrl(String infoUrl) {
        writeProperty(INFO_URL_PROPERTY, infoUrl);
    }
    public String getInfoUrl() {
        return (String)readProperty(INFO_URL_PROPERTY);
    }

    public void setLicense(String license) {
        writeProperty(LICENSE_PROPERTY, license);
    }
    public String getLicense() {
        return (String)readProperty(LICENSE_PROPERTY);
    }

    public void setSource(String source) {
        writeProperty(SOURCE_PROPERTY, source);
    }
    public String getSource() {
        return (String)readProperty(SOURCE_PROPERTY);
    }

    public void setTcFileID(Integer tcFileID) {
        writeProperty(TC_FILE_ID_PROPERTY, tcFileID);
    }
    public Integer getTcFileID() {
        return (Integer)readProperty(TC_FILE_ID_PROPERTY);
    }

    public void setFormat(MotorDataFormat format) {
        setToOneTarget(FORMAT_PROPERTY, format, true);
    }

    public MotorDataFormat getFormat() {
        return (MotorDataFormat)readProperty(FORMAT_PROPERTY);
    }


    public void setMotor(Motor motor) {
        setToOneTarget(MOTOR_PROPERTY, motor, true);
    }

    public Motor getMotor() {
        return (Motor)readProperty(MOTOR_PROPERTY);
    }


}
