package club.ncr.website.db.auto;

import club.ncr.website.db.Motor;
import club.ncr.website.db.MotorName;
import org.apache.cayenne.CayenneDataObject;

import java.util.List;

/**
 * Class _MotorImpulse was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _MotorImpulse extends CayenneDataObject {

    public static final String IMPULSE_PROPERTY = "impulse";
    public static final String MOTOR_NAMES_PROPERTY = "motorNames";
    public static final String MOTORS_PROPERTY = "motors";

    public static final String ID_PK_COLUMN = "ID";

    public void setImpulse(String impulse) {
        writeProperty(IMPULSE_PROPERTY, impulse);
    }
    public String getImpulse() {
        return (String)readProperty(IMPULSE_PROPERTY);
    }

    public void addToMotorNames(MotorName obj) {
        addToManyTarget(MOTOR_NAMES_PROPERTY, obj, true);
    }
    public void removeFromMotorNames(MotorName obj) {
        removeToManyTarget(MOTOR_NAMES_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<MotorName> getMotorNames() {
        return (List<MotorName>)readProperty(MOTOR_NAMES_PROPERTY);
    }


    public void addToMotors(Motor obj) {
        addToManyTarget(MOTORS_PROPERTY, obj, true);
    }
    public void removeFromMotors(Motor obj) {
        removeToManyTarget(MOTORS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Motor> getMotors() {
        return (List<Motor>)readProperty(MOTORS_PROPERTY);
    }


}
