package club.ncr.website.db.auto;

import club.ncr.website.db.NcrMember;
import org.apache.cayenne.CayenneDataObject;

import java.util.List;

/**
 * Class _NcrMemberStatus was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _NcrMemberStatus extends CayenneDataObject {

    public static final String NAME_PROPERTY = "name";
    public static final String MEMBERS_PROPERTY = "members";

    public static final String ID_PK_COLUMN = "ID";

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void addToMembers(NcrMember obj) {
        addToManyTarget(MEMBERS_PROPERTY, obj, true);
    }
    public void removeFromMembers(NcrMember obj) {
        removeToManyTarget(MEMBERS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<NcrMember> getMembers() {
        return (List<NcrMember>)readProperty(MEMBERS_PROPERTY);
    }


}
