package club.ncr.website.db.auto;

import club.ncr.website.db.NcrMember;
import club.ncr.website.db.NcrRole;
import org.apache.cayenne.CayenneDataObject;

/**
 * Class _NcrMemberRole was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _NcrMemberRole extends CayenneDataObject {

    public static final String MEMBER_PROPERTY = "member";
    public static final String ROLE_PROPERTY = "role";

    public static final String ID_PK_COLUMN = "ID";

    public void setMember(NcrMember member) {
        setToOneTarget(MEMBER_PROPERTY, member, true);
    }

    public NcrMember getMember() {
        return (NcrMember)readProperty(MEMBER_PROPERTY);
    }


    public void setRole(NcrRole role) {
        setToOneTarget(ROLE_PROPERTY, role, true);
    }

    public NcrRole getRole() {
        return (NcrRole)readProperty(ROLE_PROPERTY);
    }


}
