package club.ncr.website.db.auto;

import org.apache.cayenne.CayenneDataObject;

import java.util.Date;

/**
 * Class _NcrAlert was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _NcrAlert extends CayenneDataObject {

    public static final String CREATED_PROPERTY = "created";
    public static final String MESSAGE_PROPERTY = "message";
    public static final String TYPE_PROPERTY = "type";
    public static final String VALID_THRU_PROPERTY = "validThru";

    public static final String ID_PK_COLUMN = "id";

    public void setCreated(Date created) {
        writeProperty(CREATED_PROPERTY, created);
    }
    public Date getCreated() {
        return (Date)readProperty(CREATED_PROPERTY);
    }

    public void setMessage(String message) {
        writeProperty(MESSAGE_PROPERTY, message);
    }
    public String getMessage() {
        return (String)readProperty(MESSAGE_PROPERTY);
    }

    public void setType(String type) {
        writeProperty(TYPE_PROPERTY, type);
    }
    public String getType() {
        return (String)readProperty(TYPE_PROPERTY);
    }

    public void setValidThru(Date validThru) {
        writeProperty(VALID_THRU_PROPERTY, validThru);
    }
    public Date getValidThru() {
        return (Date)readProperty(VALID_THRU_PROPERTY);
    }

}
