package club.ncr.website.db.auto;

import club.ncr.website.db.Contact;
import club.ncr.website.db.NcrMemberRole;
import club.ncr.website.db.NcrMemberStatus;
import club.ncr.website.db.NcrMemberType;
import org.apache.cayenne.CayenneDataObject;

import java.util.Date;
import java.util.List;

/**
 * Class _NcrMember was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _NcrMember extends CayenneDataObject {

    public static final String EXPIRES_PROPERTY = "expires";
    public static final String ID_PROPERTY = "id";
    public static final String JOINED_PROPERTY = "joined";
    public static final String NAR_MEMBER_ID_PROPERTY = "narMemberID";
    public static final String TRIPOLI_MEMBER_ID_PROPERTY = "tripoliMemberID";
    public static final String CONTACT_PROPERTY = "contact";
    public static final String MEMBER_ROLES_PROPERTY = "memberRoles";
    public static final String STATUS_PROPERTY = "status";
    public static final String TYPE_PROPERTY = "type";

    public static final String ID_PK_COLUMN = "ID";

    public void setExpires(Date expires) {
        writeProperty(EXPIRES_PROPERTY, expires);
    }
    public Date getExpires() {
        return (Date)readProperty(EXPIRES_PROPERTY);
    }

    public void setId(Integer id) {
        writeProperty(ID_PROPERTY, id);
    }
    public Integer getId() {
        return (Integer)readProperty(ID_PROPERTY);
    }

    public void setJoined(Date joined) {
        writeProperty(JOINED_PROPERTY, joined);
    }
    public Date getJoined() {
        return (Date)readProperty(JOINED_PROPERTY);
    }

    public void setNarMemberID(Integer narMemberID) {
        writeProperty(NAR_MEMBER_ID_PROPERTY, narMemberID);
    }
    public Integer getNarMemberID() {
        return (Integer)readProperty(NAR_MEMBER_ID_PROPERTY);
    }

    public void setTripoliMemberID(Integer tripoliMemberID) {
        writeProperty(TRIPOLI_MEMBER_ID_PROPERTY, tripoliMemberID);
    }
    public Integer getTripoliMemberID() {
        return (Integer)readProperty(TRIPOLI_MEMBER_ID_PROPERTY);
    }

    public void setContact(Contact contact) {
        setToOneTarget(CONTACT_PROPERTY, contact, true);
    }

    public Contact getContact() {
        return (Contact)readProperty(CONTACT_PROPERTY);
    }


    public void addToMemberRoles(NcrMemberRole obj) {
        addToManyTarget(MEMBER_ROLES_PROPERTY, obj, true);
    }
    public void removeFromMemberRoles(NcrMemberRole obj) {
        removeToManyTarget(MEMBER_ROLES_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<NcrMemberRole> getMemberRoles() {
        return (List<NcrMemberRole>)readProperty(MEMBER_ROLES_PROPERTY);
    }


    public void setStatus(NcrMemberStatus status) {
        setToOneTarget(STATUS_PROPERTY, status, true);
    }

    public NcrMemberStatus getStatus() {
        return (NcrMemberStatus)readProperty(STATUS_PROPERTY);
    }


    public void setType(NcrMemberType type) {
        setToOneTarget(TYPE_PROPERTY, type, true);
    }

    public NcrMemberType getType() {
        return (NcrMemberType)readProperty(TYPE_PROPERTY);
    }


}
