package club.ncr.cayenne.auto;

import club.ncr.cayenne.Motor;
import org.apache.cayenne.CayenneDataObject;

import java.util.List;

/**
 * Class _MotorDiameter was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _MotorDiameter extends CayenneDataObject {

    public static final String DIAMETER_PROPERTY = "diameter";
    public static final String MOTORS_PROPERTY = "motors";

    public static final String ID_PK_COLUMN = "ID";

    public void setDiameter(Integer diameter) {
        writeProperty(DIAMETER_PROPERTY, diameter);
    }
    public Integer getDiameter() {
        return (Integer)readProperty(DIAMETER_PROPERTY);
    }

    public void addToMotors(Motor obj) {
        addToManyTarget(MOTORS_PROPERTY, obj, true);
    }
    public void removeFromMotors(Motor obj) {
        removeToManyTarget(MOTORS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Motor> getMotors() {
        return (List<Motor>)readProperty(MOTORS_PROPERTY);
    }


}
