package club.ncr.cayenne.auto;

import club.ncr.cayenne.MotorData;
import org.apache.cayenne.CayenneDataObject;

import java.util.List;

/**
 * Class _MotorDataFormat was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _MotorDataFormat extends CayenneDataObject {

    public static final String FILE_EXTENSION_PROPERTY = "fileExtension";
    public static final String NAME_PROPERTY = "name";
    public static final String MOTOR_DATA_PROPERTY = "motorData";

    public static final String ID_PK_COLUMN = "ID";

    public void setFileExtension(String fileExtension) {
        writeProperty(FILE_EXTENSION_PROPERTY, fileExtension);
    }
    public String getFileExtension() {
        return (String)readProperty(FILE_EXTENSION_PROPERTY);
    }

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void addToMotorData(MotorData obj) {
        addToManyTarget(MOTOR_DATA_PROPERTY, obj, true);
    }
    public void removeFromMotorData(MotorData obj) {
        removeToManyTarget(MOTOR_DATA_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<MotorData> getMotorData() {
        return (List<MotorData>)readProperty(MOTOR_DATA_PROPERTY);
    }


}
